version: '3' # docker-compose 파일의 버전
services: # 서비스 정의 섹션
  web: # web 서비스 정의
    build: # 빌드 설정
      context: . # 빌드 컨텍스트를 현재 디렉터리로 설정
      dockerfile: ./dockerfile/dockerfile.gunicorn # 사용할 Dockerfile의 위치
    image: kimjenny/practice:web # 생성될 이미지의 이름과 태그
    volumes: # 볼륨 설정
      - static_volume:/app/static # 정적 파일을 위한 볼륨
      - media_volume:/app/media # 미디어 파일을 위한 볼륨
    ports: # 포트 매핑
      - "8000:8000" # 호스트의 8000 포트를 컨테이너의 8000 포트에 연결

  nginx: # nginx 서비스 정의
    build: # 빌드 설정
      context: . # 빌드 컨텍스트를 현재 디렉터리로 설정
      dockerfile: ./dockerfile/dockerfile.nginx # 사용할 Dockerfile의 위치
    image: kimjenny/practice:nginx # 생성될 이미지의 이름과 태그
    volumes: # 볼륨 설정
      - static_volume:/app/static # 정적 파일을 위한 볼륨
      - media_volume:/app/media # 미디어 파일을 위한 볼륨
    ports: # 포트 매핑
      - "80:80" # 호스트의 80 포트를 컨테이너의 80 포트에 연결

volumes: # 볼륨 정의 섹션
  static_volume: # 정적 파일을 저장할 볼륨
  media_volume: # 미디어 파일을 저장할 볼륨