name: Django CI/CD

on:
  push:
    branches: [ product ]

jobs:
  CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create .env file
      run: |
        touch .env
        echo SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} >> .env
        echo DEBUG=${{ secrets.DJANGO_DEBUG }} >> .env
        echo API_URL=${{ secrets.DJANGO_API_URL }} >> .env
        echo WEB_URL=${{ secrets.DJANGO_WEB_URL }} >> .env
        cat .env

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile -t kimjenny/practice

    - name: Push to Docker Hub
      run: docker push kimejenny/practice

  CD:
    needs: [ CI ]
    runs-on: ubuntu-latest

    steps:
    - name: connect ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOYMENT_HOST }}
        username: ${{ secrets.DEPLOYMENT_USERNAME }}
        password: ${{ secrets.DEPLOYMENT_PASSWORD }}
        port: ${{ secrets.DEPLOYMENT_PORT }}
        script: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker-compose down
          docker-compose pull
          docker-compose up -d